D3/app/main/forms.py
from flask.ext.wtf import Form
from wtforms import FileField, SubmitField
from wtforms.validators import Required


class UploadForm(Form):
    file = FileField('CSV file', validators=[Required()])
    submit = SubmitField('Submit')
# #################################################
# Specific web forms to be added to pages are defined as classes and passed to html files for rendering
# #################################################

D3/app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap

from config import config  # this is the config.py file in the app directory

bootstrap = Bootstrap()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

D3/app/main/__init__.py
from flask import Blueprint


main = Blueprint('main', __name__, static_folder='static')  # First the blueprint name then module where located.


from . import views, errors  # imported at bottom of script to avoid circular dependencies

D3/app/main/views.py
"""
Evert application routes are stored in this module.
"""

from flask import render_template, session, redirect, url_for, flash
from . import main
from .forms import UploadForm
from werkzeug.utils import secure_filename
from pandas import read_csv
from numpy import linspace, exp, sin
from pandas import DataFrame
from bokeh.plotting import figure
from bokeh.embed import components
from bokeh.models import CustomJS, ColumnDataSource, Range1d, LinearAxis
from bokeh.models.tools import BoxSelectTool, PanTool, ResetTool, WheelZoomTool, BoxZoomTool



@main.route('/', methods=['GET'])
def index():
    return render_template('index.html')


@main.route('/upload', methods=['GET', 'POST'])
def upload():
    filename = None
    form = UploadForm()
    if form.validate_on_submit():
        filename = secure_filename(form.file.data.filename)
        form.file.data.save('app/static/uploads/' + filename)
        session['newUpload'] = filename  # This session library element serves to allow interactive feedback
        flash(filename + ' successfully uploaded to Evert.')
        return redirect(url_for('main.upload'))  # url_for() builds a URL to a specific function, html file irrelevant
    else:                                        # Now main.upload used as the function is relevant to a spec blueprint
        filename = None
    return render_template('upload.html', form=form)


# Try to directly embed into HTML whilst still making use of Bootstrap
@main.route('/plot', methods=['GET'])
def plot():
    # with open(url_for('main.static', filename='uploads/Data1.csv/'), 'r') as myfile:
    #    data = myfile.read().replace('\n', '')
    return render_template("int_scatter.html")

D3/app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Evert{% endblock %}

{% block head %}
{{ super() }}
    <script type="text/javascript" src="{{ url_for('main.static', filename='javascript/FirstOrderEyeball.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('main.static', filename='javascript/d3.js') }}"></script>
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Evert</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{ url_for('main.upload') }}">Upload</a></li>
                <li><a href="{{ url_for('main.plot') }}">Plot</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

D3/app/templates/index.html
{% extends "base.html" %}

D3/app/templates/int_scatter.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Evert{% endblock %}
{% block head %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('main.static', filename='javascript/chartGen_line.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('main.static', filename='css/charts.css') }}"
{% endblock %}
{% block body %}
    {{ super() }}
    <script>
        d3.csv( "{{ url_for('main.static', filename='uploads/Data1.csv') }}", chartGen_line)
    </script>
{% endblock %}

D3/app/templates/upload.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Evert{% endblock %}

{% block page_content %}
    <h1>Data upload page</h1>
{{ wtf.quick_form(form) }}
{% endblock %}